import ctypes


SECP256K1_FLAGS_TYPE_CONTEXT = (1 << 0)
SECP256K1_FLAGS_BIT_CONTEXT_SIGN = (1 << 9)
SECP256K1_FLAGS_BIT_CONTEXT_VERIFY = (1 << 8)
SECP256K1_CONTEXT_SIGN = (
        SECP256K1_FLAGS_TYPE_CONTEXT | SECP256K1_FLAGS_BIT_CONTEXT_SIGN
)
SECP256K1_CONTEXT_VERIFY = (
        SECP256K1_FLAGS_TYPE_CONTEXT | SECP256K1_FLAGS_BIT_CONTEXT_VERIFY
)
SECP256K1_FLAGS_TYPE_COMPRESSION = (1 << 1)
SECP256K1_FLAGS_BIT_COMPRESSION = (1 << 8)
SECP256K1_EC_COMPRESSED = (
        SECP256K1_FLAGS_TYPE_COMPRESSION | SECP256K1_FLAGS_BIT_COMPRESSION
)
SECP256K1_EC_UNCOMPRESSED = SECP256K1_FLAGS_TYPE_COMPRESSION

SECKEY_SIZE = 32
HASH32 = 32
PUBLIC_KEY_SIZE = 65
XONLY_PUBKEY_SIZE = 32
COMPRESSED_PUBLIC_KEY_SIZE = 33
DER_SIGNATURE_SIZE = 72
COMPACT_SIGNATURE_SIZE = 64

INTERNAL_PUBKEY_SIZE = 64
INTERNAL_SIGNATURE_SIZE = 64
INTERNAL_KEYPAIR_SIZE = 96
INTERNAL_RECOVERABLE_SIGNATURE_SIZE = 65

# Opaque secp256k1 data structures
secp256k1_context = ctypes.c_void_p
secp256k1_pubkey = ctypes.c_char * INTERNAL_PUBKEY_SIZE
secp256k1_ecdsa_signature = ctypes.c_char * INTERNAL_SIGNATURE_SIZE
secp256k1_xonly_pubkey = ctypes.c_char * INTERNAL_PUBKEY_SIZE
secp256k1_keypair = ctypes.c_char * INTERNAL_KEYPAIR_SIZE
secp256k1_ecdsa_recoverable_signature = ctypes.c_char * INTERNAL_RECOVERABLE_SIGNATURE_SIZE
